name: Update Readme.md
on:
  workflow_dispatch: {}
  schedule:
    - cron: "* * * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: User Node.js LTS
        uses: actions/setup-node@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Execute script
        run: npx tsx src/readme-cron-handler.ts

      - name: Commit and push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "docs: readme.md updated ${GITHUB_SHA}" || true
          git push
